version: '3.8'

services:
  toolbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toolbox_everything
    ports:
      - "8000:8000"
    volumes:
      - toolbox_uploads:/app/uploads
      - toolbox_downloads:/app/downloads
      - toolbox_logs:/app/logs
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - WERKZEUG_RUN_MAIN=true
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - toolbox_network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  toolbox_network:
    driver: bridge

volumes:
  toolbox_uploads:
    driver: local
  toolbox_downloads:
    driver: local
  toolbox_logs:
    driver: local 